import type { Metadata } from "next";
import { Inter,Poppins , } from "next/font/google";
import "./globals.css";

import FullHeader from "./components/FullHeader";
import Footer from "./components/Footer";

const inter = Inter({
  subsets:["latin"]
 });
 const poppins = Poppins({
   subsets: ['latin'],
   weight:['400','700'],
 });
 
export const metadata: Metadata = {
  title: "Furniture Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${inter.className}`}
      >
         
        <FullHeader/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
